# -*- coding: utf-8 -*-
"""8_Puzzle_BFS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ga13TG9dPzWQAWAHd98b7WC4zLc_GPDV
"""

import pandas as pd
import numpy as np

# Initial State


###################### Definations#######################

# Move up
def ActionMoveUp(CurrentNode):
  return status,node

# Move Down
def ActionMoveDown(CurrentNode):
  return status,node

# Move Left
def ActionMoveLeft(CurrentNode):
  return status,node

# Move Right
def ActionMoveRight(CurrentNode):
  return status,node

# Add Node
def AddNode(NewNode): 
  return node,nodeinfo

# Path
def generate_path(node)
  return path
#########################################################

# Run